name: CI & CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pylint
        run: poetry run pylint src --fail-under=8
      - name: Run tests
        run: poetry run coverage run -m pytest
      - name: Check coverage
        run: poetry run coverage report --fail-under=80
      - name: Run robot tests
        run: bash run_robot_tests.sh
      - name: Compose coverage report
        if: ${{ github.event_name == 'push'}}
        run: poetry run coverage xml
      - name: Report to Codecov
        if: ${{ github.event_name == 'push'}}
        run: bash <(curl -s https://codecov.io/bash)
  deploy:
    if: ${{ github.event_name == 'push'}}
    name: Deploy to Heroku staging
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "python-lukuvinkit"
          heroku_email: "rpsalmi@gmail.com"

