name: CI & CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
      - name: Compose coverage report
        run: poetry run coverage xml
      - name: Report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  deploy:
    name: Deploy to Heroku staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "python-lukuvinkit"
          heroku_email: "rpsalmi@gmail.com"

